# ==========================================================
# model/unet.yaml
# ----------------------------------------------------------
# 모델 아키텍처 관련 설정 파일
# - 모델 이름
# - 입력/출력 채널 수
# - base_channels (U-Net의 채널 수 시작점)
# - dropout (과적합 방지)
# ----------------------------------------------------------
# 다른 모델(ex. swin_unet.yaml)도 같은 구조로 추가 가능
# ==========================================================

name: "unet"
in_channels: 1
out_channels: 1
base_channels: 16
dropout: 0.0