# ==========================================================
# eval.yaml
# ----------------------------------------------------------
# 평가(Evaluation) 관련 설정 파일
# - batch size (검증 시 메모리 최적화용)
# - 향후 평가 메트릭, 평가 데이터 버전 등을 확장 가능
# ----------------------------------------------------------
# 테스트 시에도 동일한 구조를 공유하는 것을 권장
# ==========================================================

# batch_size: 4
which_run: "latest" 