# ==========================================================
# experiment.yaml
# ----------------------------------------------------------
# 공통적인 실험 환경 설정을 정의하는 파일
# - Random Seed (재현성 보장)
# - Log Level (INFO/DEBUG 등)
# ----------------------------------------------------------
# 모든 실험에서 공유되는 글로벌한 설정
# ==========================================================

seed: 42
log_level: "INFO"
