# ==========================================================
# tracking.yaml
# ----------------------------------------------------------
# MLflow 관련 추적/저장소 설정을 정의하는 파일
# - MLflow Tracking URI (어디에 실험 기록을 저장할지)
# - MLflow Experiment 이름 (실험 그룹 구분)
# - 공통으로 붙일 Tag (project, owner 등)
# ----------------------------------------------------------
# 주의: 여기 있는 값은 .env 파일의 환경변수로도 대체 가능
# ==========================================================

mlflow:
  tracking_uri: file:./mlruns
  experiment: iris_demo
tags:
  project: "iris"
  owner: "solo"