# ==========================================================
# train.yaml
# ----------------------------------------------------------
# 학습(Training) 관련 설정 파일
# - 학습 epoch 수
# - batch size
# - learning rate (lr)
# - optimizer 종류 (adam/sgd 등)
# - save_top_k (성능 좋은 모델 몇 개 저장할지)
# ----------------------------------------------------------
# 실험마다 hyperparameter 조정 시 여기서 변경
# ==========================================================

# epochs: 3
# batch_size: 4
# lr: 1e-3
# optimizer: "adam"
# save_top_k: 1

seed: 42
test_size: 0.2
model:
  name: "logreg"        # "logreg" | "rf"
  params:
    C: 1.0
    max_iter: 200